# Generated by Django 3.2.9 on 2021-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20211111_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='product',
            name='base_64_qr_code',
            field=models.TextField(blank=True),
        ),
    ]
